xFormers not available
xFormers not available
2025-08-10 22:39:01,400 INFO     [evaluate_stereo.py:469] Loading checkpoint...
2025-08-10 22:39:01,400 INFO     [evaluate_stereo.py:470] ./checkpoints/mix_all.pth
2025-08-10 22:39:03,027 INFO     [evaluate_stereo.py:485] Done loading checkpoint
Traceback (most recent call last):
  File "evaluate_stereo.py", line 487, in <module>
    model.cuda()
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 918, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 918, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/cuda/__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
