The following values were not passed to `accelerate launch` and had defaults used instead:
		More than one GPU was found, enabling multi-GPU training.
		If this was unintended please pass in `--num_processes=1`.
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
xFormers not available
xFormers not available
xFormers not available
xFormers not available
xFormers not available
xFormers not available
xFormers not available
xFormers not available
  0%|          | 0/152 [00:00<?, ?it/s]Error executing job with overrides: []
Traceback (most recent call last):
  File "train_whu.py", line 137, in main
    disp_init_pred, disp_preds, depth_mono = model(left, right, iters=cfg.train_iters)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1519, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1355, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/misc/home6/s0214/MonSter/core/monster.py", line 382, in forward
    geo_encoding_volume = self.cost_agg(gwc_volume, features_left)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/misc/home6/s0214/MonSter/core/monster.py", line 125, in forward
    conv1 = torch.cat((conv2_up, conv1), dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 48 but got size 47 for tensor number 1 in the list.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Error executing job with overrides: []
Traceback (most recent call last):
  File "train_whu.py", line 137, in main
    disp_init_pred, disp_preds, depth_mono = model(left, right, iters=cfg.train_iters)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1519, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1355, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/misc/home6/s0214/MonSter/core/monster.py", line 382, in forward
    geo_encoding_volume = self.cost_agg(gwc_volume, features_left)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/misc/home6/s0214/MonSter/core/monster.py", line 125, in forward
    conv1 = torch.cat((conv2_up, conv1), dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 48 but got size 47 for tensor number 1 in the list.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
  0%|          | 0/152 [00:07<?, ?it/s]
Error executing job with overrides: []
Traceback (most recent call last):
  File "train_whu.py", line 137, in main
    disp_init_pred, disp_preds, depth_mono = model(left, right, iters=cfg.train_iters)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1519, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1355, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/misc/home6/s0214/MonSter/core/monster.py", line 382, in forward
    geo_encoding_volume = self.cost_agg(gwc_volume, features_left)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/misc/home6/s0214/MonSter/core/monster.py", line 125, in forward
    conv1 = torch.cat((conv2_up, conv1), dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 48 but got size 47 for tensor number 1 in the list.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Error executing job with overrides: []
Traceback (most recent call last):
  File "train_whu.py", line 137, in main
    disp_init_pred, disp_preds, depth_mono = model(left, right, iters=cfg.train_iters)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1519, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1355, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/misc/home6/s0214/MonSter/core/monster.py", line 382, in forward
    geo_encoding_volume = self.cost_agg(gwc_volume, features_left)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/misc/home6/s0214/MonSter/core/monster.py", line 125, in forward
    conv1 = torch.cat((conv2_up, conv1), dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 48 but got size 47 for tensor number 1 in the list.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2025-08-10 23:46:59,032] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 336879 closing signal SIGTERM
[2025-08-10 23:46:59,033] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 336881 closing signal SIGTERM
[2025-08-10 23:46:59,033] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 336882 closing signal SIGTERM
[2025-08-10 23:46:59,561] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 1 (pid: 336880) of binary: /home/s0214/.conda/envs/monster/bin/python
Traceback (most recent call last):
  File "/home/s0214/.conda/envs/monster/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/accelerate/commands/launch.py", line 1159, in launch_command
    multi_gpu_launcher(args)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/accelerate/commands/launch.py", line 793, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/s0214/.conda/envs/monster/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_whu.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-08-10_23:46:59
  host      : tesla-v100
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 336880)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
